src/HashReviews/Transaction/ReviewBundle/Entity/Review.php
<?php
namespace HashReviews\Transaction\ReviewBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

class Review
{

    // custom methods

    public function getAuthorAddress() {
        if($this->getRe() == "to")
            return $this->getFromAddress();
        elseif($this->getRe() == "from")
            return $this->getToAddress();
        else 
            return false;

    }

    public function getReAddress() {
        if($this->getRe() == "to")
            return $this->getToAddress();
        elseif($this->getRe() == "from")
            return $this->getFromAddress();
        else 
            return false;

    }

    public function getReadUrl($controller) {

        return $controller->get('router')->generate('read', array(
            're' => $this->getRe(),
            'tx_hash' => $this->getTxHash(),
            'from_address' => $this->getFromAddress(),
            'to_address' => $this->getToAddress()

        ));
    }



    // end custom methods

    /**
     * @var string
     */
    private $tx_hash;

    /**
     * @var string
     */
    private $from_address;

    /**
     * @var string
     */
    private $to_address;

    /**
     * @var string
     */
    private $re;

    /**
     * @var \DateTime
     */
    private $tx_date;

    /**
     * @var string
     */
    private $tx_amount;

    /**
     * @var integer
     */
    private $rating;

    /**
     * @var string
     */
    private $review;

    /**
     * @var string
     */
    private $version;

    /**
     * @var string
     */
    private $review_message;

    /**
     * @var string
     */
    private $random;

    /**
     * @var string
     */
    private $review_message_hash;

    /**
     * @var string
     */
    private $signature;

    /**
     * @var string
     */
    private $status;

    /**
     * @var \DateTime
     */
    private $created_at;

    /**
     * @var \DateTime
     */
    private $updated_at;


    /**
     * Set tx_hash
     *
     * @param string $txHash
     * @return Review
     */
    public function setTxHash($txHash)
    {
        $this->tx_hash = $txHash;

        return $this;
    }

    /**
     * Get tx_hash
     *
     * @return string 
     */
    public function getTxHash()
    {
        return $this->tx_hash;
    }

    /**
     * Set from_address
     *
     * @param string $fromAddress
     * @return Review
     */
    public function setFromAddress($fromAddress)
    {
        $this->from_address = $fromAddress;

        return $this;
    }

    /**
     * Get from_address
     *
     * @return string 
     */
    public function getFromAddress()
    {
        return $this->from_address;
    }

    /**
     * Set to_address
     *
     * @param string $toAddress
     * @return Review
     */
    public function setToAddress($toAddress)
    {
        $this->to_address = $toAddress;

        return $this;
    }

    /**
     * Get to_address
     *
     * @return string 
     */
    public function getToAddress()
    {
        return $this->to_address;
    }

    /**
     * Set re
     *
     * @param string $re
     * @return Review
     */
    public function setRe($re)
    {
        $this->re = $re;

        return $this;
    }

    /**
     * Get re
     *
     * @return string 
     */
    public function getRe()
    {
        return $this->re;
    }

    /**
     * Set tx_date
     *
     * @param \DateTime $txDate
     * @return Review
     */
    public function setTxDate($txDate)
    {
        $this->tx_date = $txDate;

        return $this;
    }

    /**
     * Get tx_date
     *
     * @return \DateTime 
     */
    public function getTxDate()
    {
        return $this->tx_date;
    }

    /**
     * Set tx_amount
     *
     * @param string $txAmount
     * @return Review
     */
    public function setTxAmount($txAmount)
    {
        $this->tx_amount = $txAmount;

        return $this;
    }

    /**
     * Get tx_amount
     *
     * @return string 
     */
    public function getTxAmount()
    {
        return $this->tx_amount;
    }

    /**
     * Set rating
     *
     * @param integer $rating
     * @return Review
     */
    public function setRating($rating)
    {
        $this->rating = $rating;

        return $this;
    }

    /**
     * Get rating
     *
     * @return integer 
     */
    public function getRating()
    {
        return $this->rating;
    }

    /**
     * Set review
     *
     * @param string $review
     * @return Review
     */
    public function setReview($review)
    {
        $this->review = $review;

        return $this;
    }

    /**
     * Get review
     *
     * @return string 
     */
    public function getReview()
    {
        return $this->review;
    }

    /**
     * Set version
     *
     * @param string $version
     * @return Review
     */
    public function setVersion($version)
    {
        $this->version = $version;

        return $this;
    }

    /**
     * Get version
     *
     * @return string 
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Set review_message
     *
     * @param string $reviewMessage
     * @return Review
     */
    public function setReviewMessage($reviewMessage)
    {
        $this->review_message = $reviewMessage;

        return $this;
    }

    /**
     * Get review_message
     *
     * @return string 
     */
    public function getReviewMessage()
    {
        return $this->review_message;
    }

    /**
     * Set random
     *
     * @param string $random
     * @return Review
     */
    public function setRandom($random)
    {
        $this->random = $random;

        return $this;
    }

    /**
     * Get random
     *
     * @return string 
     */
    public function getRandom()
    {
        return $this->random;
    }

    /**
     * Set review_message_hash
     *
     * @param string $reviewMessageHash
     * @return Review
     */
    public function setReviewMessageHash($reviewMessageHash)
    {
        $this->review_message_hash = $reviewMessageHash;

        return $this;
    }

    /**
     * Get review_message_hash
     *
     * @return string 
     */
    public function getReviewMessageHash()
    {
        return $this->review_message_hash;
    }

    /**
     * Set signature
     *
     * @param string $signature
     * @return Review
     */
    public function setSignature($signature)
    {
        $this->signature = $signature;

        return $this;
    }

    /**
     * Get signature
     *
     * @return string 
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * Set status
     *
     * @param string $status
     * @return Review
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return string 
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set created_at
     *
     * @param \DateTime $createdAt
     * @return Review
     */
    public function setCreatedAt($createdAt)
    {
        $this->created_at = $createdAt;

        return $this;
    }

    /**
     * Get created_at
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Set updated_at
     *
     * @param \DateTime $updatedAt
     * @return Review
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updated_at = $updatedAt;

        return $this;
    }

    /**
     * Get updated_at
     *
     * @return \DateTime 
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }
    /**
     * @var string
     */
    private $sign_link;


    /**
     * Set sign_link
     *
     * @param string $signLink
     * @return Review
     */
    public function setSignLink($signLink)
    {
        $this->sign_link = $signLink;

        return $this;
    }

    /**
     * Get sign_link
     *
     * @return string 
     */
    public function getSignLink()
    {
        return $this->sign_link;
    }
}

src/HashReviews/Transaction/ReviewBundle/Resources/views/Default/flashbag.html.twig
{% for flashMessage in app.session.flashbag.get('error') %}
    <div style="color: red; border: solid 2px; padding: 10px; margin: 5px 0; font-weight: bold">
        {{ flashMessage }}
    </div>
{% endfor %}

src/HashReviews/Transaction/ReviewBundle/Resources/views/Default/footer.html.twig
  	<footer style="font-size: 12px; margin-top: 50px">
  	<b>info (at) hash.reviews</b>
  	</footer>
  	</div>
  </body>
</html>

src/HashReviews/Transaction/ReviewBundle/Resources/views/Default/header.html.twig
<!DOCTYPE html>
<html>
  <head>
    <title>Hash.Reviews</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  </head>
  <body>
  	<div class="container" style="max-width:800px">
  	<header>
  		<h1 style="font-size: 20px"><a href="{{ path('index') }}" style="text-decoration: none" >hash.reviews</a> <a style="font-size: 15px; margin-left: 10px; text-decoration: none" href="{{ path('page', {'slug': 'doc'}) }}" />info</a> {% include "HashReviewsTransactionReviewBundle:Default:searchForm.html.twig" %}</h1>
  	</header>

src/HashReviews/Transaction/ReviewBundle/Resources/views/Default/index.html.twig
{% include "HashReviewsTransactionReviewBundle:Default:header.html.twig" %}

<h2>Enter transaction details.</h2>

<p>In <a href="https://coinbase.com/accounts">CoinBase</a> you can get these details by clicking on a transaction in your account and then 'Advanced Details'.</p>

{% include "HashReviewsTransactionReviewBundle:Default:flashbag.html.twig" %}

{{ form(form) }}

{% include "HashReviewsTransactionReviewBundle:Default:footer.html.twig" %}

src/HashReviews/Transaction/ReviewBundle/Resources/views/Default/page.doc.html.twig
{% include "HashReviewsTransactionReviewBundle:Default:header.html.twig" %}

<h2>Documentation</h2>


<h3>API</h3>

<p>Although we do not provide a full API yet we do provide convenient entry points to our web interface to make it easier to read and create reviews.<p>

<h4>Read Reviews</h4>

<p><b>Single Review:</b><br />
<b>http://hash.reviews/&lt;re&gt;/&lt;tx_hash&gt;/&lt;from_address&gt;/&lt;to_address&gt;</b><br />
<b>&lt;re&gt;</b> can be 'to' or 'from', indicates which bitcoin address is being reviewed.
</p>

<p><b>List of Reviews:</b><br />
<b>http://hash.reviews/reviews/&lt;address or tx_hash&gt;</b><br />
<b>&lt;address&gt;</b> is the address reviewed, useful for vendors and providers who always receive bitcoin at the same address.
</p>

<h4>Create or Update a Review</h4>

<p><b>http://hash.reviews/init/&lt;re&gt;/&lt;tx_hash&gt;/&lt;from_address&gt;/&lt;to_address&gt;/&lt;sign_link&gt;</b><br />
<b>&lt;sign_link&gt;</b> is optional, it should be a wallet link for signing a message and will be displayed on the sign review page if it matches the referring domain.  The other parameters are just like the single review read link above.  Using this 'init' link allows someone to skip the whole first step of review creation and proceed directly to rating and review entry.  Useful for requesting reviews from your customers.
</p>

<h3>Reviews for Multiple Addresses?</h3>
<p>If you normally receive payments on multiple addresses then please contact us about setting up an account that will allow you to link all your addresses and reviews and prove your ownership.</p>

<h3>Technical Details</h3>
<p>Updating a review over-writes the existing review.  We do not keep a history of review revisions nor a review block chain.</p>
<p>Transactions with multiple input and output addresses can have multiple reviews which may be useful for single transactions where more than one party is involved in sending or receiving funds, like escrow.</p>




{% include "HashReviewsTransactionReviewBundle:Default:footer.html.twig" %}

src/HashReviews/Transaction/ReviewBundle/Resources/views/Default/read.html.twig
{% include "HashReviewsTransactionReviewBundle:Default:header.html.twig" %}

<h2>Review</h2>
<p>Date: {{ review.createdAt|date('m/d/Y') }}
{% if review.updatedAt < review.createdAt %}
(updated: {{ review.updatedAt|date('m/d/Y') }})
{% endif %}
</p>



<p>Rating: {{ review.rating }}/5</p>

<p>{{ review.review|nl2br }}</p>
<hr />
<h4>Transaction Details:</h4>
<p>Date: {{ review.txDate|date('m/d/Y') }}</p>
<p>Estimated Amount: {{ review.txAmount }} BTC</p>
<p>
{% if review.re == 'to' %}
This review was authored by someone who sent bitcoin to this address:
{% else %}
This review was authored by someone who received bitcoin from this address:
{% endif %} <b>{{ review.reAddress }}</b>
</p>
<div id="moreLink">
	<a href="javascript:;" onclick="$('#moreDetails').toggle();$('#moreLink').toggle();">more details</a>
</div>
<div id="moreDetails" style="display: none">
<p>Hash: <b>{{ review.txHash }}</b></p>
<p>View on: <a href="https://blockchain.info/tx/{{ review.txHash }}">BlockChain.info</a>
<p><a href="{{ revise_link }}">Revise Review</a> You'll need to be able to sign it with address: <b>{{ review.authorAddress }}</b></p>


<h3>Full Review Message:</h3>
<p>You can verify this message and signature with any bitcoind instance, or with the wallet tools at <a href="https://blockchain.info/wallet">BlockChain.info</a><br />  Version 1.0 hash is sha256 twice.</p>
<pre>
{{ review.reviewMessage }}
</pre>


<p>Message Hash:<br /><pre>{{ review.reviewMessageHash }}</pre></p>

<p>Signature:<br /><pre>{{ review.signature }}</pre></p>

<p>Review Author / {% if review.re == 'to' %}Bitcoin Sender{% else %}Bitcoin Receiver{% endif %} / Signed By :<br /><pre>{{ review.authorAddress }}</pre></p>

<p><a href="javascript:;" onclick="$('#moreDetails').toggle();$('#moreLink').toggle();">less details</a></p>

</div>

{% include "HashReviewsTransactionReviewBundle:Default:footer.html.twig" %}

src/HashReviews/Transaction/ReviewBundle/Resources/views/Default/request.html.twig
{% include "HashReviewsTransactionReviewBundle:Default:header.html.twig" %}

<h2>Request a Review</h2>

<p>Send this link to request a signed transaction review from someone who 
{% if data.re == "to" %}
 sent bitcoin to you.
{% else %}
 received bitcoin from you.
{% endif %}
<br />
<a href="{{ link }}">Review Link</a>

{% include "HashReviewsTransactionReviewBundle:Default:footer.html.twig" %}

src/HashReviews/Transaction/ReviewBundle/Resources/views/Default/review.html.twig
{% include "HashReviewsTransactionReviewBundle:Default:header.html.twig" %}

<h2>Rate and Review a transaction.</h2>

{% include "HashReviewsTransactionReviewBundle:Default:flashbag.html.twig" %}

{% if existing_link %}
	<p>Review already exists though you can revise it if you can sign it.<br />
	<a href="{{ existing_link }}" target="_blank">Read Existing Review</a>.</p> 

{% endif %}

{{ form(form) }}
<p></p>

<p>Please provide an accurate rating and review.  You  may address the {% if review.re == 'to' %}goods or services received{% else %}client/customer{% endif %} and/or the transaction itself.</p>

<p>If you have been pressured to change your review please let us know and/or add that information to your review.</p>

<p><a href="http://en.wikipedia.org/wiki/Shill">Shill</a> reviews will be blocked.</b>


{% include "HashReviewsTransactionReviewBundle:Default:footer.html.twig" %}

src/HashReviews/Transaction/ReviewBundle/Resources/views/Default/reviews.html.twig
{% include "HashReviewsTransactionReviewBundle:Default:header.html.twig" %}

<h2>Reviews</h2>
<h4>For {% if is_tx %} transaction hash {% else %} bitcoin address {% endif %}: {{ query }}</h4>

{% include "HashReviewsTransactionReviewBundle:Default:flashbag.html.twig" %}

{% if reviews %}
<table class="table table-striped">
<tr><th>Date</th><th>Rating</th><th>Review</th></tr>
{% for review in reviews %}
    <tr>
    	<td>{{ review.createdAt|date('m/d/Y') }}</td>
    	<td>{{review.rating}}/5</td>
    	<td><div style="height: 20px; overflow: hidden;">{{ review.review }}</div>
    		<a href="{{ app.request.baseUrl }}/{{review.re}}/{{review.txHash}}/{{review.fromAddress}}/{{review.toAddress}}">read more</a>
    	</td>
    </tr>

{% endfor %}

</table>
{% endif %}

{% include "HashReviewsTransactionReviewBundle:Default:footer.html.twig" %}

src/HashReviews/Transaction/ReviewBundle/Resources/views/Default/searchForm.html.twig
<div style="text-align: top; float: right; font-size: 15px; width: 400px;">
<input type="button" style="float: right; margin-left: 5px;" value="search" />
<input type="text" id="query" class="form-control" style="float: right; height: 22px; width: 300px;" placeholder="enter address or transaction hash"  value="{% if query is defined %}{{ query }}{% endif %}">

</div>

<script type="text/javascript">
	$("#query").change(function() {
	  	window.location = "{{ app.request.baseUrl }}/reviews/" + $("#query").val();
	});

</script>

src/HashReviews/Transaction/ReviewBundle/Resources/views/Default/sign.html.twig
{% include "HashReviewsTransactionReviewBundle:Default:header.html.twig" %}

<h2>Sign Your Review.</h2>

<p>Copy the entire hash and use your wallet to sign it as a message.  When you have the signature paste it below.</p>

{% if review.signLink %}
<a href="{{ review.signLink }}">Click to get your signature</a>
{% else %}
<p>In CoinBase go to <a href="https://coinbase.com/addresses" target="_blank">Settings > Addresses</a>, find this address: <b>{% if review.re == 'to' %}{{ review.fromAddress}}{% else %}{{ review.fromTo}}{% endif %}</b>, click the 'Details' button and on the next page click the "sign a message" link.</p>

{% endif %}

<p><b>The review must be signed with this address: {% if review.re == 'to' %} {{ review.fromAddress}} {% else %} {{ review.fromTo}} {% endif %}</b></p>

{% include "HashReviewsTransactionReviewBundle:Default:flashbag.html.twig" %}

{{ form(form) }}

{% include "HashReviewsTransactionReviewBundle:Default:footer.html.twig" %}

src/HashReviews/Transaction/ReviewBundle/Resources/views/Default/success.html.twig
{% include "HashReviewsTransactionReviewBundle:Default:header.html.twig" %}

<h2>Finished!</h2>

<p><a href="{{ link }}">Read Your Review</a></p>

<p>Message and signature verified using <a href="https://blockchain.info/api">BlockChain.info API</a>.  Transaction information:<br />
<a href="https://blockchain.info/tx/{{ review.txHash }}">https://blockchain.info/tx/{{ review.txHash }}</a>

{% include "HashReviewsTransactionReviewBundle:Default:footer.html.twig" %}